export default {
    FETCH_WHISKY_PENDING:"FETCH_WHISKY_PENDING", 
    FETCH_WHISKY_FULFILLED:"FETCH_WHISKY_FULFILLED", 
    FETCH_WHISKY_REJECTED:"FETCH_WHISKY_REJECTED", 

    POST_WHISKY_PENDING: "POST_WHISKY_PENDING",
    POST_WHISKY_FULFILLED: "POST_WHISKY_FULFILLED",
    POST_WHISKY_REJECTED: "POST_WHISKY_REJECTED",

    PUT_WHISKY_PENDING: "PUT_WHISKY_PENDING",
    PUT_WHISKY_FULFILLED: "PUT_WHISKY_FULFILLED",
    PUT_WHISKY_REJECTED: "PUT_WHISKY_REJECTED",

    DELETE_WHISKY_PENDING: "DELETE_WHISKY_PENDING",
    DELETE_WHISKY_FULFILLED: "DELETE_WHISKY_FULFILLED",
    DELETE_WHISKY_REJECTED: "DELETE_WHISKY_REJECTED",

    FETCH_WHISKY_DETAILS_PENDING:"FETCH_WHISKY_DETAILS_PENDING", 
    FETCH_WHISKY_DETAILS_FULFILLED:"FETCH_WHISKY_DETAILS_FULFILLED", 
    FETCH_WHISKY_DETAILS_REJECTED:"FETCH_WHISKY_DETAILS_REJECTED", 
    
    OPEN_SNACKBAR: "OPEN_SNACKBAR",
    CLOSE_SNACKBAR: "CLOSE_SNACKBAR"

}