export default {

    // WHISKY
    FETCH_WHISKY_PENDING:"FETCH_WHISKY_PENDING", 
    FETCH_WHISKY_FULFILLED:"FETCH_WHISKY_FULFILLED", 
    FETCH_WHISKY_REJECTED:"FETCH_WHISKY_REJECTED", 

    POST_WHISKY_PENDING: "POST_WHISKY_PENDING",
    POST_WHISKY_FULFILLED: "POST_WHISKY_FULFILLED",
    POST_WHISKY_REJECTED: "POST_WHISKY_REJECTED",

    PUT_WHISKY_PENDING: "PUT_WHISKY_PENDING",
    PUT_WHISKY_FULFILLED: "PUT_WHISKY_FULFILLED",
    PUT_WHISKY_REJECTED: "PUT_WHISKY_REJECTED",

    DELETE_WHISKY_PENDING: "DELETE_WHISKY_PENDING",
    DELETE_WHISKY_FULFILLED: "DELETE_WHISKY_FULFILLED",
    DELETE_WHISKY_REJECTED: "DELETE_WHISKY_REJECTED",

    FETCH_WHISKY_DETAILS_PENDING:"FETCH_WHISKY_DETAILS_PENDING", 
    FETCH_WHISKY_DETAILS_FULFILLED:"FETCH_WHISKY_DETAILS_FULFILLED", 
    FETCH_WHISKY_DETAILS_REJECTED:"FETCH_WHISKY_DETAILS_REJECTED", 
    
    // TAGS
    FILTER_BY_TAG_ID:"FILTER_BY_TAG_ID",
    DISABLE_FILTER:"DISABLE_FILTER",
    FETCH_TAG_PENDING:"FETCH_TAG_PENDING", 
    FETCH_TAG_FULFILLED:"FETCH_TAG_FULFILLED", 
    FETCH_TAG_REJECTED:"FETCH_TAG_REJECTED", 

    POST_TAG_PENDING: "POST_TAG_PENDING",
    POST_TAG_FULFILLED: "POST_TAG_FULFILLED",
    POST_TAG_REJECTED: "POST_TAG_REJECTED",

    PUT_TAG_PENDING: "PUT_TAG_PENDING",
    PUT_TAG_FULFILLED: "PUT_TAG_FULFILLED",
    PUT_TAG_REJECTED: "PUT_TAG_REJECTED",

    DELETE_TAG_PENDING: "DELETE_TAG_PENDING",
    DELETE_TAG_FULFILLED: "DELETE_TAG_FULFILLED",
    DELETE_TAG_REJECTED: "DELETE_TAG_REJECTED",

    FETCH_WHISKY_TAGS_PENDING:"FETCH_WHISKY_TAGS_PENDING", 
    FETCH_WHISKY_TAGS_FULFILLED:"FETCH_WHISKY_TAGS_FULFILLED", 
    FETCH_WHISKY_TAGS_REJECTED:"FETCH_WHISKY_TAGS_REJECTED", 


    OPEN_SNACKBAR: "OPEN_SNACKBAR",
    CLOSE_SNACKBAR: "CLOSE_SNACKBAR"

}